name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Setup | wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - name: Setup | just
      uses: extractions/setup-just@v1
    - name: Setup | Python 3.10
      uses: actions/setup-python@v3.0.0
      with:
        python-version: '3.10'
    - name: Setup | toml, pyyaml, pylint, pylint-quotes
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          toml
          pyyaml
          pylint
          pylint-quotes
    - name: Setup | Node 16.14.2
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '16.14.2'
    - name: Setup | CI Install
      run: just ci
    - name: Build | Lint
      run: just lint --verbose
    - name: Build | Build
      run: just build
    - name: Build | Test (WIP)
      run: echo "No test to run"
    - name: Release | Package
      if: github.event_name != 'pull_request'
      run: just release
    - name: Release | Release
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        body_path: release/RELEASE_NOTES.txt
        files: |
          release/*.vsix
          release/README.md
    - name: Release | Deploy Web App(WIP)
      if: github.event_name != 'pull_request' && github.ref_name == 'main'
      run: echo "Nothing to deploy"
